name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  check_if_version_upgraded:
    name: Check if package version has been upgraded
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      has_updated: ${{ steps.check-version.outputs.has_updated }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Get the current package version
      - id: get-version
        name: Get current version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      # Check if version has been updated
      - id: check-version
        name: Check if version updated
        run: |
          # Get the previous commit hash
          PREV_COMMIT=$(git rev-parse HEAD^)
          echo "Previous commit: $PREV_COMMIT"
          
          # Get the previous version from the previous commit
          PREV_VERSION=$(git show $PREV_COMMIT:package.json | node -p "JSON.parse(require('fs').readFileSync(0)).version")
          echo "Previous version: $PREV_VERSION"
          
          CURRENT_VERSION=${{ steps.get-version.outputs.version }}
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$PREV_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version has been updated from $PREV_VERSION to $CURRENT_VERSION"
            echo "has_updated=true" >> $GITHUB_OUTPUT
          else
            echo "Version has not changed"
            echo "has_updated=false" >> $GITHUB_OUTPUT
          fi

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    needs:
      - check_if_version_upgraded
    # We create release only if the version in the package.json has been upgraded
    if: |
      needs.check_if_version_upgraded.outputs.has_updated == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - name: Build docs
        run: npx typedoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          
  publish-js:
    name: Publish package
    runs-on: ubuntu-latest
    needs:
      - check_if_version_upgraded
    # We create release only if the version in the package.json has been upgraded
    if: |
      needs.check_if_version_upgraded.outputs.has_updated == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install Dependencies
        id: deps
        run: |
          pnpm install --frozen-lockfile
      - name: Build Release
        id: build_release
        run: |
          pnpm build
      - name: Run Tests
        id: tests
        run: |
          pnpm test
          
      - name: Publish Release
        if: steps.tests.outcome == 'success'
        run: |
          if [ "$NODE_AUTH_TOKEN" = "" ]; then
            echo "You need a NPM_TOKEN secret in order to publish."
            exit 1
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN} > .npmrc
          
          EXTRA_ARGS=""
          if [[ $VERSION == *"alpha."* ]] || [[ $VERSION == *"beta."* ]] || [[ $VERSION == *"rc."* ]]; then
            echo "Is pre-release version"
            EXTRA_ARGS="$EXTRA_ARGS --dist-tag next"
          fi
          
          # Use --force-publish to ensure all packages are published
          # This preserves the original workflow where all packages are released
          # with the version number from the root package.json
          npx lerna publish ${VERSION} --yes --force-publish --no-git-tag-version $EXTRA_ARGS
          
      - name: Create GitHub Release
        if: steps.tests.outcome == 'success'
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.check_if_version_upgraded.outputs.version }}
          tag_name: v${{ needs.check_if_version_upgraded.outputs.version }}
          target_commitish: main
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          VERSION: ${{ needs.check_if_version_upgraded.outputs.version }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
